name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Thử chuyển sang ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Dùng version mới nhất của checkout

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Package Electron App
      run: npm run package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tool_spam_groups
        path: dist/
